<?php return array (
  0 => 'CREATE TABLE `xiaozu_collect` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` int(20) NOT NULL,
  `collectid` int(20) NOT NULL COMMENT \'对应商品/店铺ID\',
  `collecttype` int(1) NOT NULL COMMENT \'0店铺  1商品\',
  `shopuid` int(20) NOT NULL COMMENT \'店铺所有者ID\',
  `orderid` int(11) NOT NULL DEFAULT \'100\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=232 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'93\',\'2\',\'7\',\'1\',\'2\',\'0\')',
  2 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'97\',\'8\',\'6\',\'0\',\'2\',\'0\')',
  3 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'95\',\'2\',\'11\',\'1\',\'2\',\'0\')',
  4 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'108\',\'2\',\'6\',\'0\',\'2\',\'0\')',
  5 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'94\',\'2\',\'10\',\'1\',\'2\',\'0\')',
  6 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'109\',\'2\',\'8\',\'0\',\'3\',\'0\')',
  7 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'111\',\'16\',\'9\',\'0\',\'13\',\'0\')',
  8 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'112\',\'18\',\'9\',\'0\',\'13\',\'0\')',
  9 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'113\',\'21\',\'9\',\'0\',\'13\',\'0\')',
  10 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'115\',\'21\',\'10\',\'0\',\'4\',\'0\')',
  11 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'116\',\'24\',\'11\',\'0\',\'29\',\'0\')',
  12 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'117\',\'24\',\'12\',\'0\',\'30\',\'0\')',
  13 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'124\',\'48\',\'15\',\'0\',\'35\',\'0\')',
  14 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'119\',\'38\',\'9\',\'0\',\'13\',\'0\')',
  15 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'120\',\'38\',\'11\',\'0\',\'29\',\'0\')',
  16 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'125\',\'48\',\'11\',\'0\',\'29\',\'0\')',
  17 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'126\',\'48\',\'9\',\'0\',\'13\',\'0\')',
  18 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'129\',\'48\',\'12\',\'0\',\'30\',\'0\')',
  19 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'128\',\'48\',\'16\',\'0\',\'41\',\'0\')',
  20 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'130\',\'50\',\'9\',\'0\',\'13\',\'0\')',
  21 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'131\',\'43\',\'22\',\'0\',\'43\',\'0\')',
  22 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'132\',\'67\',\'9\',\'0\',\'13\',\'100\')',
  23 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'133\',\'73\',\'9\',\'0\',\'13\',\'2\')',
  24 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'134\',\'73\',\'12\',\'0\',\'30\',\'1\')',
  25 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'135\',\'69\',\'9\',\'0\',\'13\',\'100\')',
  26 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'137\',\'69\',\'12\',\'0\',\'30\',\'100\')',
  27 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'138\',\'76\',\'9\',\'0\',\'13\',\'100\')',
  28 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'141\',\'2\',\'9\',\'0\',\'13\',\'100\')',
  29 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'199\',\'152\',\'9\',\'0\',\'13\',\'100\')',
  30 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'143\',\'80\',\'9\',\'0\',\'13\',\'100\')',
  31 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'145\',\'84\',\'15\',\'0\',\'35\',\'100\')',
  32 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'146\',\'84\',\'21\',\'0\',\'48\',\'100\')',
  33 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'202\',\'191\',\'21\',\'0\',\'48\',\'100\')',
  34 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'197\',\'96\',\'18\',\'0\',\'44\',\'100\')',
  35 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'187\',\'96\',\'9\',\'0\',\'13\',\'100\')',
  36 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'186\',\'31\',\'21\',\'0\',\'48\',\'100\')',
  37 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'196\',\'96\',\'12\',\'0\',\'30\',\'100\')',
  38 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'195\',\'96\',\'15\',\'0\',\'35\',\'100\')',
  39 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'179\',\'91\',\'21\',\'0\',\'48\',\'100\')',
  40 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'180\',\'91\',\'9\',\'0\',\'13\',\'100\')',
  41 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'181\',\'91\',\'15\',\'0\',\'35\',\'100\')',
  42 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'182\',\'91\',\'12\',\'0\',\'30\',\'100\')',
  43 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'183\',\'92\',\'15\',\'0\',\'35\',\'100\')',
  44 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'200\',\'176\',\'21\',\'0\',\'48\',\'100\')',
  45 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'201\',\'176\',\'12\',\'0\',\'30\',\'100\')',
  46 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'203\',\'192\',\'9\',\'0\',\'13\',\'100\')',
  47 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'205\',\'206\',\'9\',\'0\',\'13\',\'100\')',
  48 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'206\',\'250\',\'9\',\'0\',\'13\',\'111\')',
  49 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'207\',\'250\',\'21\',\'0\',\'48\',\'100\')',
  50 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'208\',\'250\',\'15\',\'0\',\'35\',\'100\')',
  51 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'209\',\'250\',\'12\',\'0\',\'30\',\'100\')',
  52 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'210\',\'250\',\'19\',\'0\',\'47\',\'100\')',
  53 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'211\',\'250\',\'20\',\'0\',\'46\',\'100\')',
  54 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'212\',\'250\',\'25\',\'0\',\'61\',\'100\')',
  55 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'213\',\'383\',\'9\',\'0\',\'13\',\'100\')',
  56 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'214\',\'383\',\'21\',\'0\',\'48\',\'100\')',
  57 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'220\',\'10\',\'21\',\'0\',\'48\',\'100\')',
  58 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'219\',\'10\',\'15\',\'0\',\'35\',\'100\')',
  59 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'221\',\'10\',\'9\',\'0\',\'13\',\'100\')',
  60 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'226\',\'16\',\'128\',\'1\',\'2\',\'100\')',
  61 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'227\',\'16\',\'169\',\'1\',\'2\',\'100\')',
  62 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'228\',\'16\',\'170\',\'1\',\'2\',\'100\')',
  63 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'229\',\'16\',\'168\',\'1\',\'2\',\'100\')',
  64 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'230\',\'16\',\'211\',\'1\',\'0\',\'100\')',
  65 => 'INSERT INTO `xiaozu_collect`(`id`,`uid`,`collectid`,`collecttype`,`shopuid`,`orderid`) VALUES(\'231\',\'16\',\'203\',\'1\',\'2\',\'100\')',
)?>