<?php return array (
  0 => 'CREATE TABLE `xiaozu_marketcate` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL COMMENT \'目录名称\',
  `keywd` varchar(50) DEFAULT NULL COMMENT \'关键字\',
  `desc` varchar(255) DEFAULT NULL COMMENT \'描述\',
  `parent_id` int(20) NOT NULL DEFAULT \'0\' COMMENT \'上级ID  0为1级目录\',
  `shopid` int(20) DEFAULT NULL,
  `orderid` int(5) NOT NULL DEFAULT \'999\',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=47 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'2\',\'生活日用\',\'\',\'\',\'0\',\'\',\'999\')',
  2 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'3\',\'饮品饮料\',\'\',\'\',\'0\',\'\',\'999\')',
  3 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'4\',\'美味小吃\',\'\',\'\',\'0\',\'\',\'999\')',
  4 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'5\',\'糖果巧克力\',\'\',\'\',\'0\',\'\',\'999\')',
  5 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'6\',\'进口食品\',\'\',\'\',\'0\',\'\',\'999\')',
  6 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'7\',\'面包饼干\',\'\',\'\',\'0\',\'\',\'999\')',
  7 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'18\',\'速食泡面\',\'\',\'\',\'0\',\'\',\'999\')',
  8 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'17\',\'咖啡茶品\',\'\',\'\',\'0\',\'\',\'999\')',
  9 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'19\',\'休闲食品\',\'\',\'\',\'0\',\'\',\'999\')',
  10 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'20\',\'锅巴\',\'\',\'\',\'19\',\'\',\'999\')',
  11 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'21\',\'瓜子\',\'\',\'\',\'19\',\'\',\'999\')',
  12 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'22\',\'桶装泡面\',\'\',\'\',\'18\',\'\',\'999\')',
  13 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'23\',\'面包\',\'\',\'\',\'7\',\'\',\'999\')',
  14 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'24\',\'仙贝\',\'\',\'\',\'7\',\'\',\'999\')',
  15 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'25\',\'奶茶\',\'\',\'\',\'17\',\'\',\'999\')',
  16 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'26\',\'水果\',\'\',\'\',\'19\',\'\',\'999\')',
  17 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'29\',\'42454\',\'\',\'\',\'0\',\'\',\'999\')',
  18 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'33\',\'你\',\'\',\'\',\'0\',\'\',\'999\')',
  19 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'31\',\'进口水果\',\'\',\'\',\'26\',\'\',\'999\')',
  20 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'32\',\'本地水果\',\'\',\'\',\'26\',\'\',\'999\')',
  21 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'34\',\'华润\',\'\',\'\',\'23\',\'\',\'999\')',
  22 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'35\',\'酒水饮料\',\'\',\'\',\'0\',\'44\',\'1\')',
  23 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'15\',\'生活服务\',\'\',\'\',\'0\',\'44\',\'4\')',
  24 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'9\',\'新鲜即食\',\'\',\'\',\'0\',\'44\',\'1\')',
  25 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'8\',\'鲜花预定\',\'\',\'\',\'0\',\'44\',\'3\')',
  26 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'36\',\'饮料\',\'\',\'\',\'35\',\'44\',\'5\')',
  27 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'37\',\'啤酒\',\'\',\'\',\'35\',\'44\',\'1\')',
  28 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'38\',\'水果\',\'\',\'\',\'9\',\'44\',\'7\')',
  29 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'39\',\'海鲜\',\'\',\'\',\'9\',\'44\',\'1\')',
  30 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'40\',\'肉类\',\'\',\'\',\'9\',\'44\',\'2\')',
  31 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'41\',\'电风扇\',\'\',\'\',\'8\',\'44\',\'10\')',
  32 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'42\',\'净化器\',\'\',\'\',\'8\',\'44\',\'1\')',
  33 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'43\',\'加湿器\',\'\',\'\',\'8\',\'44\',\'2\')',
  34 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'45\',\'贝壳类\',\'\',\'\',\'0\',\'55\',\'1\')',
  35 => 'INSERT INTO `xiaozu_marketcate`(`id`,`name`,`keywd`,`desc`,`parent_id`,`shopid`,`orderid`) VALUES(\'46\',\'贝壳\',\'\',\'\',\'45\',\'55\',\'2\')',
)?>