<?php return array (
  0 => 'CREATE TABLE `xiaozu_goodstype` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `shopid` int(20) NOT NULL COMMENT \'店铺ID\',
  `name` varchar(50) NOT NULL COMMENT \'分类名称\',
  `orderid` int(3) NOT NULL DEFAULT \'0\',
  `cattype` int(1) NOT NULL DEFAULT \'1\' COMMENT \'1外卖 2订台\',
  PRIMARY KEY (`id`),
  KEY `shopid` (`shopid`)
) ENGINE=MyISAM AUTO_INCREMENT=70 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'53\',\'9\',\'招牌菜\',\'1\',\'0\')',
  2 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'27\',\'12\',\'零食\',\'0\',\'0\')',
  3 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'51\',\'13\',\'商品2\',\'1\',\'0\')',
  4 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'29\',\'21\',\'西餐\',\'0\',\'0\')',
  5 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'50\',\'13\',\'商品1\',\'0\',\'0\')',
  6 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'31\',\'20\',\'盖浇饭\',\'0\',\'0\')',
  7 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'32\',\'15\',\'瓶装奶\',\'1\',\'0\')',
  8 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'34\',\'30\',\'素菜\',\'0\',\'0\')',
  9 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'35\',\'30\',\'荤菜\',\'1\',\'0\')',
  10 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'62\',\'48\',\'快餐\',\'0\',\'0\')',
  11 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'37\',\'32\',\'分类1\',\'0\',\'0\')',
  12 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'38\',\'32\',\'分类2\',\'1\',\'0\')',
  13 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'39\',\'32\',\'分类3\',\'2\',\'0\')',
  14 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'40\',\'36\',\'闽南菜\',\'0\',\'0\')',
  15 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'41\',\'17\',\'凉菜\',\'0\',\'0\')',
  16 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'42\',\'17\',\'热菜\',\'1\',\'0\')',
  17 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'43\',\'17\',\'小吃\',\'2\',\'0\')',
  18 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'44\',\'37\',\'test\',\'0\',\'0\')',
  19 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'46\',\'39\',\'889\',\'0\',\'0\')',
  20 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'47\',\'39\',\'的撒打算\',\'1\',\'0\')',
  21 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'52\',\'9\',\'盖浇饭\',\'0\',\'0\')',
  22 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'48\',\'41\',\'套餐\',\'0\',\'0\')',
  23 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'49\',\'25\',\'中餐\',\'0\',\'0\')',
  24 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'54\',\'14\',\'ces\',\'0\',\'0\')',
  25 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'55\',\'11\',\'饮料\',\'0\',\'0\')',
  26 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'56\',\'11\',\'休闲食品\',\'2\',\'0\')',
  27 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'57\',\'9\',\'铁板烧\',\'2\',\'0\')',
  28 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'58\',\'9\',\'家常小炒\',\'3\',\'0\')',
  29 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'60\',\'46\',\'风味菜\',\'0\',\'0\')',
  30 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'63\',\'9\',\'下次V\',\'4\',\'0\')',
  31 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'64\',\'52\',\'推荐\',\'0\',\'0\')',
  32 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'65\',\'54\',\'叶菜类\',\'1\',\'0\')',
  33 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'68\',\'57\',\'贝壳类\',\'0\',\'0\')',
  34 => 'INSERT INTO `xiaozu_goodstype`(`id`,`shopid`,`name`,`orderid`,`cattype`) VALUES(\'69\',\'58\',\'瓶装奶\',\'0\',\'0\')',
)?>