<?php return array (
  0 => 'CREATE TABLE `xiaozu_admin` (
  `uid` int(5) NOT NULL auto_increment,
  `username` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `time` int(11) NOT NULL,
  `logintime` int(11) NOT NULL,
  `loginip` varchar(30) default NULL,
  `limit` text,
  `groupid` int(20) NOT NULL default \'1\',
  PRIMARY KEY  (`uid`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8',
  1 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'2\',\'admin\',\'21232f297a57a5a743894a0e4a801fc3\',\'1371349333\',\'1408184679\',\'127.0.0.1\',\'siteset,seo_setsave,limitset,savelimitset,footlink,savefootlink,toplink,savetoplink,jflimitset,manegelist,manegeadd,editmanege,manegesave,delmanege,memberlist,addmember,editmember,membersave,delmember,oauthlist,deloauth,shoplist,shoplistw,shoptype,addshoptype,editshoptype,saveshoptype,delshoptype,arealist,addarea,eidtarea,savearea,cxsign,addcxsign,editcxsign,orderlist,ordertotal,markettj,marketorder,orderyjin,commentlist,delcommlist,asklist,delask,askshoplist,singlelist,addsingle,savesingle,delsingle,adv,addadv,advtype,giftlist,addgift,gifttype,addgifttype,giftlog,emailset,smsset,sendtasklist,sendtask,cardlist,addcard,juanlist,addjuan,excomm,pmes,loginlist,paylist,othertpl,ordertodayw,ordertoday,ordersend,basedata,rebkdata,market,addmarket,editmarket,delmarket,addmarkettype,delmarkettype,listmarkettype,friendlink,shoptopatt,wxset,wxback,wxmenu,printlog\',\'1\')',
  2 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'6\',\'test\',\'098f6bcd4621d373cade4e832627b4f6\',\'1383984203\',\'1403660180\',\'1.193.102.2\',\'siteset,seo_setsave,limitset,savelimitset,footlink,savefootlink,toplink,savetoplink,memberlist,addmember,editmember,membersave,delmember,shoplist,shoptype,addshoptype,editshoptype,saveshoptype,delshoptype,arealist,addarea,eidtarea,savearea,goodssign,addgoodssign,editgoodsign,savegoodssign,delgoossign,shopsign,addshosign,editshosign,cxsign,addcxsign,editcxsign,commentlist\',\'6\')',
  3 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'7\',\'px2010\',\'77819a7c0961535ae9a890a9d62116d7\',\'1384004836\',\'1384004851\',\'127.0.0.1\',\'orderlist\',\'1\')',
  4 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'8\',\'guanghe\',\'eb1f3562dc1fd5f20b5e370189b85b00\',\'1390643466\',\'0\',\'\',\'siteset,seo_setsave,limitset,savelimitset,footlink,savefootlink,toplink,savetoplink,jflimitset,manegelist,manegeadd,editmanege,manegesave,delmanege,memberlist,addmember,editmember,membersave,delmember,oauthlist,deloauth,shoplist,shoptype,addshoptype,editshoptype,saveshoptype,delshoptype,arealist,addarea,eidtarea,savearea,cxsign,addcxsign,editcxsign,orderlist,ordertotal,markettj,marketorder,orderyjin,commentlist,delcommlist,asklist,delask,askshoplist,singlelist,addsingle,savesingle,delsingle,adv,addadv,advtype,giftlist,addgift,gifttype,addgifttype,giftlog,emailset,smsset,sendtasklist,sendtask,cardlist,addcard,juanlist,addjuan,excomm,pmes,loginlist,paylist,othertpl,ordertodayw,ordertoday,basedata,rebkdata,market,addmarket,editmarket,delmarket,addmarkettype,delmarkettype,listmarkettype,friendlink,shoptopatt\',\'1\')',
  5 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'9\',\'songly\',\'8f378e2c0562f3a162431d9d3a61264a\',\'1397368132\',\'1397369609\',\'61.178.103.133\',\'siteset,seo_setsave,limitset,savelimitset,footlink,savefootlink,toplink,savetoplink,jflimitset,manegelist,manegeadd,editmanege,manegesave,delmanege,memberlist,addmember,editmember,membersave,delmember,oauthlist,deloauth,shoplist,shoplistw,shoptype,addshoptype,editshoptype,saveshoptype,delshoptype,arealist,addarea,eidtarea,savearea,cxsign,addcxsign,editcxsign,orderlist,ordertotal,markettj,marketorder,orderyjin,commentlist,delcommlist,asklist,delask,askshoplist,singlelist,addsingle,savesingle,delsingle,adv,addadv,advtype,giftlist,addgift,gifttype,addgifttype,giftlog,emailset,smsset,sendtasklist,sendtask,cardlist,addcard,juanlist,addjuan,excomm,pmes,loginlist,paylist,othertpl,ordertodayw,ordertoday,basedata,rebkdata,market,addmarket,editmarket,delmarket,addmarkettype,delmarkettype,listmarkettype,friendlink,shoptopatt,wxset,wxback,wxmenu,printlog\',\'1\')',
  6 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'10\',\'yisi\',\'8f378e2c0562f3a162431d9d3a61264a\',\'1397369643\',\'1397369652\',\'61.178.103.133\',\'siteset,footlink,addcxsign,editcxsign,orderlist,markettj,marketorder,orderyjin\',\'1\')',
  7 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'11\',\'shangjia\',\'e10adc3949ba59abbe56e057f20f883e\',\'1397538550\',\'1397538568\',\'219.155.159.148\',\'shoplist,shoplistw,shoptype,addshoptype,editshoptype,saveshoptype,delshoptype\',\'1\')',
  8 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'14\',\'123456\',\'e10adc3949ba59abbe56e057f20f883e\',\'1403255487\',\'1403255504\',\'101.24.1.218\',\'\',\'1\')',
  9 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'15\',\'ceshi\',\'e10adc3949ba59abbe56e057f20f883e\',\'1403585082\',\'0\',\'\',\'\',\'1\')',
  10 => 'INSERT INTO `xiaozu_admin`(`uid`,`username`,`password`,`time`,`logintime`,`loginip`,`limit`,`groupid`) VALUES(\'16\',\'3656\',\'14678db82874f1456031fcc05a3afaf6\',\'1403874963\',\'0\',\'\',\'\',\'4\')',
)?>